name: Basic Docker Build

on:
  push:
    branches:
      - 'main'
    pull_request:


jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: fdidustintaylor
          password: iYMFXcKEvqX9Nq$hM7TjRJxn$S$2apso

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: fdidustintaylor/basic-docker-build:latest