services:
  allhands22:
    image: "${TESTING_IMAGE}"
  
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      allhands22:
        condition: service_started

    # run all your tests here against the allhands22 service
    command: curl --fail http://allhands22:80 || exit 1